
export default {
  AA: {name: "Afar", nativeName: "Afaraf"},
  AB: {name: "Abkhaz", nativeName: "аҧсуа бызшәа, аҧсшәа"},
  AE: {name: "Avestan", nativeName: "avesta"},
  AF: {name: "Afrikaans", nativeName: "Afrikaans"},
  AK: {name: "Akan", nativeName: "Akan"},
  AM: {name: "Amharic", nativeName: "አማርኛ"},
  AN: {name: "Aragonese", nativeName: "aragonés"},
  AR: {name: "Arabic", nativeName: "العربية"},
  AS: {name: "Assamese", nativeName: "অসমীয়া"},
  AV: {name: "Avaric", nativeName: "авар мацӀ, магӀарул мацӀ"},
  AY: {name: "Aymara", nativeName: "aymar aru"},
  AZ: {name: "Azerbaijani", nativeName: "azərbaycan dili"},
  BA: {name: "Bashkir", nativeName: "башҡорт теле"},
  BE: {name: "Belarusian", nativeName: "беларуская мова"},
  BG: {name: "Bulgarian", nativeName: "български език"},
  BH: {name: "Bihari", nativeName: "भोजपुरी"},
  BI: {name: "Bislama", nativeName: "Bislama"},
  BM: {name: "Bambara", nativeName: "bamanankan"},
  BN: {name: "Bengali, Bangla", nativeName: "বাংলা"},
  BO: {name: "Tibetan Standard, Tibetan, Central", nativeName: "བོད་ཡིག"},
  BR: {name: "Breton", nativeName: "brezhoneg"},
  BS: {name: "Bosnian", nativeName: "bosanski jezik"},
  CA: {name: "Catalan", nativeName: "català"},
  CE: {name: "Chechen", nativeName: "нохчийн мотт"},
  CH: {name: "Chamorro", nativeName: "Chamoru"},
  CO: {name: "Corsican", nativeName: "corsu, lingua corsa"},
  CR: {name: "Cree", nativeName: "ᓀᐦᐃᔭᐍᐏᐣ"},
  CS: {name: "Czech", nativeName: "čeština, český jazyk"},
  CU: {name: "Old Church Slavonic, Church Slavonic, Old Bulgarian", nativeName: "ѩзыкъ словѣньскъ"},
  CV: {name: "Chuvash", nativeName: "чӑваш чӗлхи"},
  CY: {name: "Welsh", nativeName: "Cymraeg"},
  DA: {name: "Danish", nativeName: "dansk"},
  DE: {name: "German", nativeName: "Deutsch"},
  DV: {name: "Divehi, Dhivehi, Maldivian", nativeName: "ދިވެހި"},
  DZ: {name: "Dzongkha", nativeName: "རྫོང་ཁ"},
  EE: {name: "Ewe", nativeName: "Eʋegbe"},
  EL: {name: "Greek (modern)", nativeName: "ελληνικά"},
  EN: {name: "English", nativeName: "English"},
  EO: {name: "Esperanto", nativeName: "Esperanto"},
  ES: {name: "Spanish", nativeName: "Español"},
  ET: {name: "Estonian", nativeName: "eesti, eesti keel"},
  EU: {name: "Basque", nativeName: "euskara, euskera"},
  FA: {name: "Persian (Farsi)", nativeName: "فارسی"},
  FF: {name: "Fula, Fulah, Pulaar, Pular", nativeName: "Fulfulde, Pulaar, Pular"},
  FI: {name: "Finnish", nativeName: "suomi, suomen kieli"},
  FJ: {name: "Fijian", nativeName: "vosa Vakaviti"},
  FO: {name: "Faroese", nativeName: "føroyskt"},
  FR: {name: "French", nativeName: "français, langue française"},
  FY: {name: "Western Frisian", nativeName: "Frysk"},
  GA: {name: "Irish", nativeName: "Gaeilge"},
  GD: {name: "Scottish Gaelic, Gaelic", nativeName: "Gàidhlig"},
  GL: {name: "Galician", nativeName: "galego"},
  GN: {name: "Guaraní", nativeName: "Avañe'ẽ"},
  GU: {name: "Gujarati", nativeName: "ગુજરાતી"},
  GV: {name: "Manx", nativeName: "Gaelg, Gailck"},
  HA: {name: "Hausa", nativeName: "(Hausa) هَوُسَ"},
  HE: {name: "Hebrew (modern)", nativeName: "עברית"},
  HI: {name: "Hindi", nativeName: "हिन्दी, हिंदी"},
  HO: {name: "Hiri Motu", nativeName: "Hiri Motu"},
  HR: {name: "Croatian", nativeName: "hrvatski jezik"},
  HT: {name: "Haitian, Haitian Creole", nativeName: "Kreyòl ayisyen"},
  HU: {name: "Hungarian", nativeName: "magyar"},
  HY: {name: "Armenian", nativeName: "Հայերեն"},
  HZ: {name: "Herero", nativeName: "Otjiherero"},
  IA: {name: "Interlingua", nativeName: "Interlingua"},
  ID: {name: "Indonesian", nativeName: "Bahasa Indonesia"},
  IE: {name: "Interlingue", nativeName: "Originally called Occidental; then Interlingue after WWII"},
  IG: {name: "Igbo", nativeName: "Asụsụ Igbo"},
  II: {name: "Nuosu", nativeName: "ꆈꌠ꒿ Nuosuhxop"},
  IK: {name: "Inupiaq", nativeName: "Iñupiaq, Iñupiatun"},
  IO: {name: "Ido", nativeName: "Ido"},
  IS: {name: "Icelandic", nativeName: "Íslenska"},
  IT: {name: "Italian", nativeName: "Italiano"},
  IU: {name: "Inuktitut", nativeName: "ᐃᓄᒃᑎᑐᑦ"},
  JA: {name: "Japanese", nativeName: "日本語 (にほんご)"},
  JV: {name: "Javanese", nativeName: "ꦧꦱꦗꦮ, Basa Jawa"},
  KA: {name: "Georgian", nativeName: "ქართული"},
  KG: {name: "Kongo", nativeName: "Kikongo"},
  KI: {name: "Kikuyu, Gikuyu", nativeName: "Gĩkũyũ"},
  KJ: {name: "Kwanyama, Kuanyama", nativeName: "Kuanyama"},
  KK: {name: "Kazakh", nativeName: "қазақ тілі"},
  KL: {name: "Kalaallisut, Greenlandic", nativeName: "kalaallisut, kalaallit oqaasii"},
  KM: {name: "Khmer", nativeName: "ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ"},
  KN: {name: "Kannada", nativeName: "ಕನ್ನಡ"},
  KO: {name: "Korean", nativeName: "한국어"},
  KR: {name: "Kanuri", nativeName: "Kanuri"},
  KS: {name: "Kashmiri", nativeName: "कश्मीरी, كشميري‎"},
  KU: {name: "Kurdish", nativeName: "Kurdî, كوردی‎"},
  KV: {name: "Komi", nativeName: "коми кыв"},
  KW: {name: "Cornish", nativeName: "Kernewek"},
  KY: {name: "Kyrgyz", nativeName: "Кыргызча, Кыргыз тили"},
  LA: {name: "Latin", nativeName: "latine, lingua latina"},
  LB: {name: "Luxembourgish, Letzeburgesch", nativeName: "Lëtzebuergesch"},
  LG: {name: "Ganda", nativeName: "Luganda"},
  LI: {name: "Limburgish, Limburgan, Limburger", nativeName: "Limburgs"},
  LN: {name: "Lingala", nativeName: "Lingála"},
  LO: {name: "Lao", nativeName: "ພາສາລາວ"},
  LT: {name: "Lithuanian", nativeName: "lietuvių kalba"},
  LU: {name: "Luba-Katanga", nativeName: "Tshiluba"},
  LV: {name: "Latvian", nativeName: "latviešu valoda"},
  MG: {name: "Malagasy", nativeName: "fiteny malagasy"},
  MH: {name: "Marshallese", nativeName: "Kajin M̧ajeļ"},
  MI: {name: "Māori", nativeName: "te reo Māori"},
  MK: {name: "Macedonian", nativeName: "македонски јазик"},
  ML: {name: "Malayalam", nativeName: "മലയാളം"},
  MN: {name: "Mongolian", nativeName: "Монгол хэл"},
  MR: {name: "Marathi (Marāṭhī)", nativeName: "मराठी"},
  MS: {name: "Malay", nativeName: "bahasa Melayu, بهاس ملايو‎"},
  MT: {name: "Maltese", nativeName: "Malti"},
  MY: {name: "Burmese", nativeName: "ဗမာစာ"},
  NA: {name: "Nauruan", nativeName: "Dorerin Naoero"},
  NB: {name: "Norwegian Bokmål", nativeName: "Norsk bokmål"},
  ND: {name: "Northern Ndebele", nativeName: "isiNdebele"},
  NE: {name: "Nepali", nativeName: "नेपाली"},
  NG: {name: "Ndonga", nativeName: "Owambo"},
  NL: {name: "Dutch", nativeName: "Nederlands, Vlaams"},
  NN: {name: "Norwegian Nynorsk", nativeName: "Norsk nynorsk"},
  NO: {name: "Norwegian", nativeName: "Norsk"},
  NR: {name: "Southern Ndebele", nativeName: "isiNdebele"},
  NV: {name: "Navajo, Navaho", nativeName: "Diné bizaad"},
  NY: {name: "Chichewa, Chewa, Nyanja", nativeName: "chiCheŵa, chinyanja"},
  OC: {name: "Occitan", nativeName: "occitan, lenga d'òc"},
  OJ: {name: "Ojibwe, Ojibwa", nativeName: "ᐊᓂᔑᓈᐯᒧᐎᓐ"},
  OM: {name: "Oromo", nativeName: "Afaan Oromoo"},
  OR: {name: "Oriya", nativeName: "ଓଡ଼ିଆ"},
  OS: {name: "Ossetian, Ossetic", nativeName: "ирон æвзаг"},
  PA: {name: "(Eastern) Punjabi", nativeName: "ਪੰਜਾਬੀ"},
  PI: {name: "Pāli", nativeName: "पाऴि"},
  PL: {name: "Polish", nativeName: "język polski, polszczyzna"},
  PS: {name: "Pashto, Pushto", nativeName: "پښتو"},
  PT: {name: "Portuguese", nativeName: "Português"},
  QU: {name: "Quechua", nativeName: "Runa Simi, Kichwa"},
  RM: {name: "Romansh", nativeName: "rumantsch grischun"},
  RN: {name: "Kirundi", nativeName: "Ikirundi"},
  RO: {name: "Romanian", nativeName: "Română"},
  RU: {name: "Russian", nativeName: "Русский"},
  RW: {name: "Kinyarwanda", nativeName: "Ikinyarwanda"},
  SA: {name: "Sanskrit (Saṁskṛta)", nativeName: "संस्कृतम्"},
  SC: {name: "Sardinian", nativeName: "sardu"},
  SD: {name: "Sindhi", nativeName: "सिन्धी, سنڌي، سندھی‎"},
  SE: {name: "Northern Sami", nativeName: "Davvisámegiella"},
  SG: {name: "Sango", nativeName: "yângâ tî sängö"},
  SI: {name: "Sinhalese, Sinhala", nativeName: "සිංහල"},
  SK: {name: "Slovak", nativeName: "slovenčina, slovenský jazyk"},
  SL: {name: "Slovene", nativeName: "slovenski jezik, slovenščina"},
  SM: {name: "Samoan", nativeName: "gagana fa'a Samoa"},
  SN: {name: "Shona", nativeName: "chiShona"},
  SO: {name: "Somali", nativeName: "Soomaaliga, af Soomaali"},
  SQ: {name: "Albanian", nativeName: "Shqip"},
  SR: {name: "Serbian", nativeName: "српски језик"},
  SS: {name: "Swati", nativeName: "SiSwati"},
  ST: {name: "Southern Sotho", nativeName: "Sesotho"},
  SU: {name: "Sundanese", nativeName: "Basa Sunda"},
  SV: {name: "Swedish", nativeName: "svenska"},
  SW: {name: "Swahili", nativeName: "Kiswahili"},
  TA: {name: "Tamil", nativeName: "தமிழ்"},
  TE: {name: "Telugu", nativeName: "తెలుగు"},
  TG: {name: "Tajik", nativeName: "тоҷикӣ, toçikī, تاجیکی‎"},
  TH: {name: "Thai", nativeName: "ไทย"},
  TI: {name: "Tigrinya", nativeName: "ትግርኛ"},
  TK: {name: "Turkmen", nativeName: "Türkmen, Түркмен"},
  TL: {name: "Tagalog", nativeName: "Wikang Tagalog"},
  TN: {name: "Tswana", nativeName: "Setswana"},
  TO: {name: "Tonga (Tonga Islands)", nativeName: "faka Tonga"},
  TR: {name: "Turkish", nativeName: "Türkçe"},
  TS: {name: "Tsonga", nativeName: "Xitsonga"},
  TT: {name: "Tatar", nativeName: "татар теле, tatar tele"},
  TW: {name: "Twi", nativeName: "Twi"},
  TY: {name: "Tahitian", nativeName: "Reo Tahiti"},
  UG: {name: "Uyghur", nativeName: "ئۇيغۇرچە‎, Uyghurche"},
  UK: {name: "Ukrainian", nativeName: "Українська"},
  UR: {name: "Urdu", nativeName: "اردو"},
  UZ: {name: "Uzbek", nativeName: "Oʻzbek, Ўзбек, أۇزبېك‎"},
  VE: {name: "Venda", nativeName: "Tshivenḓa"},
  VI: {name: "Vietnamese", nativeName: "Tiếng Việt"},
  VO: {name: "Volapük", nativeName: "Volapük"},
  WA: {name: "Walloon", nativeName: "walon"},
  WO: {name: "Wolof", nativeName: "Wollof"},
  XH: {name: "Xhosa", nativeName: "isiXhosa"},
  YI: {name: "Yiddish", nativeName: "ייִדיש"},
  YO: {name: "Yoruba", nativeName: "Yorùbá"},
  ZA: {name: "Zhuang, Chuang", nativeName: "Saɯ cueŋƅ, Saw cuengh"},
  ZH: {name: "Chinese", nativeName: "中文 (Zhōngwén), 汉语, 漢語"},
  ZU: {name: "Zulu", nativeName: "isiZulu"},
};
